### ISSUE TITLE
按下抬起的事件写错了大哥

### ISSUE THREAD

**Issue by Liberations** [LvKang-insist/flutter_floating#1]
floating_view.dart中 onTapCancel 变成抬起了 onTapUp才对 。。 还有点击事件暴露出来比较有用onTap而不是 onTapDown。

**Comment by LvKang-insist** [comment]
好的，感谢指出，至于点击事件暴露的问题我考虑过，我想的是点击事件还是在悬浮窗上自己写吧，没必要暴露出来一个点击事件

**Comment by LvKang-insist** [comment]
因为你无法确定点击需要回调的是某个位置还是整个悬浮窗
