### ISSUE TITLE
你好，anroid打包后，悬浮窗始终默认在右下角

### ISSUE THREAD

**Issue by bipanfei** [LvKang-insist/flutter_floating#15]
你好，Android Studio打包后，打开APP悬浮窗始终默认在右下角，但我用Android Studio直接运行就可以，但打包APK后安装后，打开APP，悬浮窗始终默认在右下角，应该也没有混淆,请问能帮我分析下原因吗？

**Comment by LvKang-insist** [comment]
> 你好，Android Studio打包后，打开APP悬浮窗始终默认在右下角，但我用Android Studio直接运行就可以，但打包APK后安装后，打开APP，悬浮窗始终默认在右下角，应该也没有混淆,请问能帮我分析下原因吗？

你好，我没有复现到你这个问题，方便的话可以加一下我的微信 15129379467 仔细说一下
