### ISSUE TITLE
初始化自定义悬浮球位置

### ISSUE THREAD

**Issue by spakerlet** [LvKang-insist/flutter_floating#19]
页面的悬浮球在上次关闭的时候，我本地记录了一个最后的位置，只要用户不清缓存，那么下次进入页面默认在该坐标生成悬浮球，而不是每次都是左上角。这个有实现吗

**Comment by spakerlet** [comment]
是这样的，我希望初始化悬浮球生成的位置能由我传过去的坐标值控制，增加属性让我能传参，不传参就是默认设置的位置，而不是每次初始化都是默认设置的位置

**Comment by LvKang-insist** [comment]
> 是这样的，我希望初始化悬浮球生成的位置能由我传过去的坐标值控制，增加属性让我能传参，不传参就是默认设置的位置，而不是每次初始化都是默认设置的位置

好的，我会想办法改一下这块，在创建悬浮窗的时候可以传入自定义的位置，在增加一个获取悬浮窗位置的api就可以了。至于保存到本地，这个操作又开发者来完成比较合适。预计明天改完

**Comment by spakerlet** [comment]
目前我能够获取到点击悬浮球的坐标，不过有个问题，我没办法获取到拖动结束但不点击悬浮球的最后坐标，我看isShowLog这个属性有拖动结束的相关坐标，那能不能我这边传给Floating一个回调函数，每次拖动结束时都触发然后将这个details值返回给我的回调函数，达到我更新最后拖动坐标的目的

**Comment by LvKang-insist** [comment]
> 目前我能够获取到点击悬浮球的坐标，不过有个问题，我没办法获取到拖动结束但不点击悬浮球的最后坐标，我看isShowLog这个属性有拖动结束的相关坐标，那能不能我这边传给Floating一个回调函数，每次拖动结束时都触发然后将这个details值返回给我的回调函数，达到我更新最后拖动坐标的目的

我会出一个获取悬浮窗坐标的 api，移动结束的回调已经有了，关闭回调也有，你可以在这两个回调里面记录位置，我会在创建悬浮窗的时候增加一个根据传入位置进行显示就行了

**Comment by LvKang-insist** [comment]
> Reference in ne

这个功能已经加上了，你可以试一下

**Comment by spakerlet** [comment]
![image](https://github.com/LvKang-insist/flutter_floating/assets/45970995/ade42064-a241-4609-a9c7-9ce8bf5eb935)
使用onPoint，传入一个Point（50.0，50.0）会报错，提示不能这样赋值给一个可选的Point<double>?，我这样使用有问题吗
