### ISSUE TITLE
怎么固定悬浮框不让组件移动呢？

### ISSUE THREAD

**Issue by BitmapLong** [LvKang-insist/flutter_floating#21]
如题，是否需要增加一个禁止拖动的属性？

**Comment by LvKang-insist** [comment]
你好，调用 floating 的 setIsStartScroll 方法即可控制是否移动

**Comment by LvKang-insist** [comment]
> 如题，是否需要增加一个禁止拖动的属性？

你好，调用 floating 的 setIsStartScroll 方法即可控制是否移动
