### ISSUE TITLE
系统悬浮窗

### ISSUE THREAD

**Issue by sheng-di** [LvKang-insist/flutter_floating#25]
有可能实现类似于 Android 的系统全局悬浮窗（覆盖在其他应用上面）、iOS 的 Video 视频画中画功能，实现的系统级别的悬浮窗吗？

这类工作是不是只能使用原生开发了。。

**Comment by LvKang-insist** [comment]
> 有可能实现类似于 Android 的系统全局悬浮窗（覆盖在其他应用上面）、iOS 的 Video 视频画中画功能，实现的系统级别的悬浮窗吗？
> 
> 这类工作是不是只能使用原生开发了。。

是，flutter 的没办法覆盖着原生页面上面，但是原生的可以。或者让flutter获取系统级悬浮窗权限(不过这个目前不太好实现)。所以系统级的还是以原生的为主
